version: "2.2"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  rabbitmq:
    image: it490/rabbitmq
    build: services/rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    environment:
      VIRTUAL_HOST: rabbitmq.it490.localhost
      VIRTUAL_PORT: 15672

  gateway:
    image: it490/gateway
    build: services/gateway
    restart: on-failure
    environment:
      VIRTUAL_HOST: gateway.it490.localhost

  app:
    image: it490/app
    build: services/app
    restart: on-failure

  imdbscraper:
    image: it490/imdbscraper
    build: services/imdbscraper
    restart: on-failure

  weatherscraper:
    image: it490/weatherscraper
    build: services/weatherscraper
    restart: on-failure

  mysql:
    image: mariadb:10.4.8-bionic
    restart: on-failure
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: app

volumes:
  rabbitmq:
  mysql:

