using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class DungeonBuild : MonoBehaviour
{

    public struct Enemy
    {
        int id;

        string name;
        int health;
        int attack;
        int[] location;
        string[] skills;
    }

    public struct Dungeon
    {
        public int id;

        public int[,] tiles;
        public Enemy[] enemies;

        //pickups
        public string[] pickups;

        public string weatherMod;
    }

    int DUNGEON_WIDTH = 5;
    int DUNGEON_HEIGHT = 5;


    Dungeon testDung = new Dungeon()
    {
        id = 1001,
        tiles = new int[,] {{ 1, 1, 1, 1, 1 },
                            { 1, 0, 0, 0, 1 },
                            { 1, 0, 0, 0, 1 },
                            { 1, 0, 1, 0, 1 },
                            { 1, 0, 1, 0, 1 },
                            { 1, 1, 1, 1, 1 }},
        enemies = new Enemy[] { },
        pickups = new string[] { },
        weatherMod = "cloudy"
    };

    public string[] PICKUP_LIST = new string[]
    {
        //populate with all pickups





    };

    
    
    


    // Start is called before the first frame update
    void Start()
    {

        BuildDungeon(testDung);


    }

    // Update is called once per frame
    void Update()
    {
        
    }

    /** 
     * Asks RabbitMQ for a dungeon, generated by the database api
     * 
     * @return A dungeon object
     */
    Dungeon LoadDungeon()
    {
        Dungeon newDung = new Dungeon();

        //get request from rmq for dungeon

        return newDung;
    }

    /**
     * Builds the dungeon in Unity
     * 
     * @param A dungeon object
     */
    void BuildDungeon(Dungeon dung)
    {
        int s;
        //Read through tiles to set up base
        for (int i = 0; i < DUNGEON_WIDTH; i++)
        {
            for (int j = 0; j < DUNGEON_HEIGHT; j++)
            {
                //place whatever is in that spot
                if(dung.tiles[j,i]<1)
                {
                    //Spawn wall
                }

                if(dung.tiles[j,i]>1)
                {
                    //Read through pickup list
                }

                //s = dung.tiles[j,i];
            }
        }

        //Read through villans to set them down/create them


        //Place down pickups and items
    }
}
